const moviesData = [
    {
        "title": "Baazigar",
        "year": "1993",
        "genres": [
            "Crime",
            "Drama",
            "Musical"
        ],
        "ratings": [
            4,
            3,
            5,
            8,
            5,
            5,
            3,
            10,
            9,
            8,
            5,
            9,
            10,
            5,
            8,
            9,
            1,
            1,
            5,
            7,
            7,
            10,
            7,
            8,
            1,
            6,
            6,
            5,
            10,
            9
        ],
        "poster": "MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT175M",
        "releaseDate": "1993-11-12",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Widowed Madan Chopra lives a very wealthy lifestyle with two daughters, Seema and Priya. His passion is car racing, and realizing that he is not young anymore, has his last race and wins - only to find out that another competitor, Vicky Malhotra, let him win. Madan befriends Vicky, introduces him to Priya and invites him to work for him in Bombay. Vicky and Priya are attracted to each other, much to Madan's delight and he announces their marriage. Before that could happen, Seema kills herself by throwing herself down from the roof of a multi-storied building. While Madan wants to close this case due to embarrassment, Seema meets with her college friend, Police Inspector Karan, and together they begin to unravel a plot that may well end Madan and the lives of others as well.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Shah Rukh Khan",
            "Rakhee Gulzar",
            "Kajol"
        ],
        "imdbRating": 7.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg"
    },
    {
        "title": "Jodhaa Akbar",
        "year": "2008",
        "genres": [
            "Action",
            "Adventure",
            "Biography"
        ],
        "ratings": [
            7,
            2,
            3,
            8,
            6,
            1,
            4,
            2,
            1,
            10,
            6,
            3,
            7,
            4,
            4,
            1,
            3,
            9,
            5,
            10,
            2,
            6,
            9,
            1,
            3,
            7,
            9,
            7,
            3,
            9
        ],
        "poster": "MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT213M",
        "releaseDate": "2008-02-15",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jodhaa Akbar is a sixteenth century love story about a marriage of alliance that gave birth to true love between a great Mughal Emperor, Akbar and a Rajput princess, Jodhaa. Politically, success knew no bounds for Emperor Akbar, After having secured the Hindu Kush, he furthered his realm by conquest until his empire extended from Afghanistan to the Bay of Bengal, and from the Himalayas to the Godhavari River. Through a shrewd blend of tolerance, generosity and force, Akbar won the allegiance of the Rajputs, the most belligerent Hindus. But little did Akbar know that when he married Jodhaa, a fiery Rajput princess, in order to further strengthen his relations with the Rajputs, he would in turn be embarking upon a new journey - the journey of true love. The daughter of King Bharmal of Amer, Jodhaa resented being reduced to a mere political pawn in this marriage of alliance, and Akbar's biggest challenge now did not merely lie in winning battles, but in winning the love of Jodhaa - a ...                Written by\nhEmRaJ (gavin_coolhgr@hotmail.com)",
        "actors": [
            "Hrithik Roshan",
            "Aishwarya Rai Bachchan",
            "Sonu Sood"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg"
    },
    {
        "title": "Wake Up Sid",
        "year": "2009",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            7,
            10,
            6,
            7,
            3,
            3,
            1,
            4,
            10,
            2,
            6,
            3,
            6,
            1,
            6,
            7,
            8,
            4,
            10,
            9,
            10,
            4,
            6,
            2,
            5,
            6,
            2,
            4
        ],
        "poster": "MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg",
        "contentRating": "",
        "duration": "PT138M",
        "releaseDate": "2009-10-02",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In Mumbai, Sid Mehra is, in the words of his father, an arrogant, spoiled brat. He lives with a doting mother, subservient brother, and a father who covers his expenses and credit card bills. Sid takes his college finals then starts work at his father's business; he lasts less than a week before walking out. At a graduation party, he meets Aisha, newly arrived from Calcutta and set on becoming a writer. He shows her the city and helps her refurbish a rented flat. He asks if she'd like to progress from friend to something more, but she says no: he lacks ambition and isn't her type. Will her words, his exam results, a confrontation with his parents, and a break with his friends be enough to wake Sid up?                Written by\n<jhailey@hotmail.com>",
        "actors": [
            "Ranbir Kapoor",
            "Konkona Sen Sharma",
            "Supriya Pathak"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg"
    },
    {
        "title": "Saala Khadoos",
        "year": "2016",
        "genres": [
            "Action",
            "Drama",
            "Sport"
        ],
        "ratings": [
            2,
            3,
            7,
            2,
            7,
            2,
            2,
            10,
            1,
            2,
            7,
            6,
            4,
            2,
            2,
            1,
            6,
            3,
            4,
            2,
            2,
            2,
            3,
            5,
            7,
            10,
            7,
            8,
            3,
            10
        ],
        "poster": "MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT109M",
        "releaseDate": "2016-01-29",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "An under-fire boxing coach, Prabhu is transferred from Hisar in Haryana to Chennai as his bosses at the Boxing Council do not like his disrespectful rule-breaking unconventional ways. In Chennai, he chances upon the raw fighting talent of Madhi, the sibling of aspiring boxer Lakshmi. He decides to put all his effort to tame Madhie and get her to shine but he is repeatedly put off by her playfulness & distrust.                Written by\nPipingHotViews",
        "actors": [
            "Madhavan",
            "Nassar",
            "Radha Ravi"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg"
    },
    {
        "title": "Qayamat Se Qayamat Tak",
        "year": "1988",
        "genres": [
            "Action",
            "Drama",
            "Musical"
        ],
        "ratings": [
            5,
            2,
            10,
            3,
            2,
            5,
            8,
            1,
            4,
            5,
            3,
            6,
            9,
            8,
            9,
            9,
            8,
            4,
            10,
            2,
            1,
            1,
            5,
            9,
            3,
            1,
            9,
            8,
            8,
            7
        ],
        "poster": "MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg",
        "contentRating": "",
        "duration": "PT162M",
        "releaseDate": "1988-03-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Both Dhanraj Singh and Randhir Singh are two bitter and old time enemies. They faced a disastrous situation when there children, Raj and Rashmi falls deeply in love. They openly declares there hatred for one another and will do anything in there power even kill but they will not accept there children's choice. But Raj and Rashmi is dedicated to there love and is not willing to accept the fact that there dads are enemies.                Written by\ngAvInDrA (brave_loverboy2004@hotmail.com)",
        "actors": [
            "Aamir Khan",
            "Juhi Chawla",
            "Goga Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg"
    },
    {
        "title": "Delhi Belly",
        "year": "2011",
        "genres": [
            "Comedy",
            "Crime",
            "Drama"
        ],
        "ratings": [
            10,
            9,
            8,
            4,
            3,
            1,
            4,
            4,
            4,
            1,
            1,
            4,
            4,
            3,
            2,
            9,
            6,
            3,
            6,
            8,
            2,
            8,
            2,
            4,
            10,
            4,
            5,
            6,
            3,
            2
        ],
        "poster": "MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@._V1_SY360_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT103M",
        "releaseDate": "2011-07-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Delhi-based Sonia agrees to deliver a package for Vladimir Dragunsky and asks her rather unkempt and debt-ridden fianc\u00e9, Tashi Malhotra, to do it for her. Tashi, in turn, asks one of two of his room-mates, Nitin. But Nitin forgets to do so due to an upset stomach ailment commonly known as 'Delhi Belly' as well as his plan to blackmail their landlord, Manish and asks the third roommate Arup to deliver the package. A gangster, Somayajulu, who was the recipient of this package, starts by brutally questioning Vladimir, and finds out that the package may be in the possession of the trio. While Tashi must deal with his attraction for Journalist Menaka and incur the wrath of her husband, Rajiv, he still has to fully come to terms whether or not he wants to marry Sonia. And the entry of ruthless Somayajulu and his gang seriously jeopardizes any plans Tashi and his friends may have for the future.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Imran Khan",
            "Vir Das",
            "Kunaal Roy Kapur"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@._V1_SY360_SX250_AL_.jpg"
    },
    {
        "title": "Magadheera",
        "year": "2009",
        "genres": [
            "Action",
            "Drama",
            "Romance"
        ],
        "ratings": [
            10,
            9,
            2,
            8,
            4,
            9,
            1,
            9,
            7,
            8,
            1,
            4,
            10,
            3,
            7,
            2,
            1,
            2,
            1,
            3,
            1,
            8,
            9,
            4,
            1,
            9,
            10,
            9,
            10,
            9
        ],
        "poster": "MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT147M",
        "releaseDate": "2009-07-30",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In 1609 AD, Mitravinda, a princess, and Kala Bhairava, the warrior that she loved, die. 400 years later, the warrior is reincarnated as Harsha, a motorcycle stuntman. He brushes hands with a girl and sparks fly as he begins to recall his past life. Knowing that he is destined to love this young woman, he sets about trying to identify her. Indu does not remember her past life and keeps Harsha at a distance; playing tricks on him until she gets to know him better. However, just as the two begin to fall in love, a sinister force from their shared past returns!                Written by\nL. Hamre",
        "actors": [
            "Kajal Aggarwal",
            "Dev Gill",
            "Srihari"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "title": "Highway",
        "year": "2014",
        "genres": [
            "Adventure",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            8,
            8,
            5,
            2,
            8,
            10,
            8,
            8,
            8,
            1,
            4,
            2,
            5,
            5,
            7,
            6,
            10,
            9,
            10,
            3,
            5,
            4,
            8,
            5,
            1,
            4,
            5,
            1
        ],
        "poster": "MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@._V1_SY500_CR0,0,344,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT133M",
        "releaseDate": "2014-02-21",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A city girl - young, full of life - is on the highway at night with her fianc\u00e9. Suddenly, her life is swung away from the brocade and jewelry of marriage to the harsh brutality of abduction. Her life will never be the same again. The gang is in a panic; the girl is a big industrialist's daughter, his links in the corridors of power make ransom out of the question. But for the leader of this group sending her back is not an option. As the days pass by, the scenery changes, the girl feels that she has changed as well. Gradually, a strange bond begins to develop between the victim and the oppressor. It is in this captivity that she, for the first time, feels free.                Written by\nVikram Nayak",
        "actors": [
            "Alia Bhatt",
            "Randeep Hooda",
            "Durgesh Kumar"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@._V1_SY500_CR0,0,344,500_AL_.jpg"
    },
    {
        "title": "Aankhen",
        "year": "2002",
        "genres": [
            "Comedy",
            "Thriller",
            "Crime"
        ],
        "ratings": [
            6,
            9,
            1,
            10,
            7,
            2,
            6,
            2,
            5,
            10,
            8,
            4,
            4,
            4,
            3,
            1,
            7,
            4,
            2,
            7,
            8,
            4,
            1,
            10,
            10,
            1,
            1,
            4,
            1,
            1
        ],
        "poster": "MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY500_SX345_AL_.jpg",
        "contentRating": "",
        "duration": "PT165M",
        "releaseDate": "2002-04-05",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Vijay Singh Rajput (Amitabh Bachchan) is a quirky manager of Vilasrao Jefferson Bank. He is extremely strict at work and believes in pushing his workers to the limit. This means that his superiors hold him in high regard for his unblemished reputation and excellent track record. But things go terribly wrong for the honest bank manager when he finds one of his own employees trying to con the customers. At this, he loses his temper and gets physical with the employee. This doesn't go down well with his superiors and they decide that Rajput is now a liability to the bank and they sack him. Amitabh can't believe the Board of Directors and his mind is filled with revenge and what better revenge than robbing the bank himself, ironic as it may sound. He decides that he must think of a plan that will hit the bank where it hurts the most - in its safe where all the money is kept. Rajput blackmails Neha (Sushmita Sen) to use her professional skills to help his plan, to train three blind men to ...                Written by\nAnonymous",
        "actors": [
            "Amitabh Bachchan",
            "Akshay Kumar",
            "Sushmita Sen"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY500_SX345_AL_.jpg"
    },
    {
        "title": "Rockstar",
        "year": "2011",
        "genres": [
            "Drama",
            "Music",
            "Musical"
        ],
        "ratings": [
            7,
            9,
            2,
            7,
            4,
            2,
            2,
            9,
            10,
            10,
            6,
            9,
            10,
            2,
            6,
            3,
            6,
            9,
            2,
            7,
            10,
            10,
            4,
            9,
            2,
            9,
            9,
            2,
            6,
            10
        ],
        "poster": "MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@._V1_SY500_SX375_AL_.jpg",
        "contentRating": "",
        "duration": "PT159M",
        "releaseDate": "2011-11-11",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The film follows Janardhan Jhakar in a series of flashbacks and flash forwards, how the small collage boy became an international rock sensation \"Jordan\". To chase his dreams of a rockstar, the wanna-be singer his counseled that music and feelings only come with pain. In the process of which, he meets Heer, a tough on the outside and popular college girl, the both become friends, and as time passes by his dreams of music fade away as they spend time together. When heer moves away, Janardhan is thrown out of his house because of family misunderstandings. As he bides his time at a local mosque, his passion for music comes back to life. He is soon signed by a record label, where he makes more enemies than friends, his tour takes him to Prague, where he is reunited with a married Heer. Things go awry when the two share an intimate moment, and Jordan his deported to India on trespassing charges filed by Heer's husband. Now an angry painful and lonely JORDAN embarks on his journey to become...                Written by\nEros International",
        "actors": [
            "Ranbir Kapoor",
            "Nargis Fakhri",
            "Shammi Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@._V1_SY500_SX375_AL_.jpg"
    },
    {
        "title": "Piku",
        "year": "2015",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            4,
            1,
            4,
            5,
            1,
            5,
            6,
            10,
            5,
            5,
            10,
            9,
            7,
            8,
            1,
            8,
            7,
            1,
            10,
            6,
            7,
            8,
            2,
            2,
            10,
            10,
            9,
            1,
            1,
            3
        ],
        "poster": "MV5BMTUwOTMxNjc2OV5BMl5BanBnXkFtZTgwODQ4OTMxNTE@._V1_SY500_SX375_AL_.jpg",
        "contentRating": "",
        "duration": "PT123M",
        "releaseDate": "2015-05-08",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A quirky comedy about the relationship between a daughter and her aging father, whose eccentricities drive everyone crazy.",
        "actors": [
            "Amitabh Bachchan",
            "Deepika Padukone",
            "Irrfan Khan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwOTMxNjc2OV5BMl5BanBnXkFtZTgwODQ4OTMxNTE@._V1_SY500_SX375_AL_.jpg"
    },
    {
        "title": "Socha Na Tha",
        "year": "2005",
        "genres": [
            "Romance",
            "Comedy"
        ],
        "ratings": [
            6,
            7,
            4,
            3,
            4,
            8,
            6,
            1,
            7,
            1,
            3,
            7,
            1,
            6,
            8,
            6,
            5,
            10,
            5,
            2,
            8,
            8,
            5,
            1,
            7,
            1,
            1,
            10,
            2,
            10
        ],
        "poster": "MV5BMzMwNDcwNTAyOF5BMl5BanBnXkFtZTcwOTg2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT137M",
        "releaseDate": "2005-03-04",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Mr. Oberoi is a wealthy industrialist, and lives a comfortable lifestyle, with this two sons. The elder son is married, and Mr Oberoi wants his second son, Viren, to marry too. He has already selected a bride for him in Aditi Malhotra. Though Viren has always lived in his father and brother's shadows, he is quite romantic at heart, and hopes to fall in love first and then marry the girl of his choice. The presence of Aditi prevents this, and he makes all attempts not to marry her. He succeeds, the wedding arrangements are all called off. Then he meets the girl of his dreams, Karen Fernandes, and proposes marriage to her. The only setback he sees that she is a Catholic, and he, a Hindu. However, that is soon overcome. Everything seems to go on smoothly between both the families, when Viren falls out of love with Karen, and wants to cancel the wedding. When questioned about his change in mind, he responds that he is in love with Aditi. But Aditi will not have anything to do with him ...                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Abhay Deol",
            "Ayesha Takia",
            "Ayesha Jhulka"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzMwNDcwNTAyOF5BMl5BanBnXkFtZTcwOTg2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg"
    },
    {
        "title": "Devdas",
        "year": "2002",
        "genres": [
            "Musical",
            "Romance"
        ],
        "ratings": [
            1,
            6,
            6,
            7,
            8,
            5,
            1,
            1,
            4,
            7,
            1,
            9,
            9,
            6,
            5,
            2,
            10,
            5,
            9,
            7,
            1,
            8,
            3,
            4,
            7,
            1,
            10,
            6,
            3,
            7
        ],
        "poster": "MV5BY2QxMGM4Y2QtMGFmMy00ZjZkLWExMWQtNTY1Yjc0MDFjZjY0XkEyXkFqcGdeQXVyNTE0MDc0NTM@._V1_SY500_CR0,0,345,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT185M",
        "releaseDate": "2002-07-12",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The son of Zamindar Narayan Mukherjee, Devdas (Shahrukh Khan) was born with a silver spoon in his mouth. He grew up in the lush village of Taj Sonapur, where he spent his childhood, indulged by his lovely playmate Paro (Aishwarya). They grew up sharing a special relationship, in which they existed only to each other. Oblivious of all the differences of status and background, a bond that would never break grew between them. Slowly, it changed to love but it was still unsaid. But the reverie was broken when his family sent Devdas to London for education. Paro's world crashed knowing that her Devdas would be gone and she lit a diya, for it signified the fast coming back of her loved one. Years passed and Devdas returned. Devdas was besotted by her stunning beauty and longed to have her back. But Zamindar Narayan Mukherjee (Vijay Crishna), Devdas' father, met Paro's mother Sumitra's (Kiran Kher) marriage proposal with condescending arrogance. It caused a rift between the families and even...                Written by\nAnonymous",
        "actors": [
            "Shah Rukh Khan",
            "Madhuri Dixit",
            "Aishwarya Rai Bachchan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BY2QxMGM4Y2QtMGFmMy00ZjZkLWExMWQtNTY1Yjc0MDFjZjY0XkEyXkFqcGdeQXVyNTE0MDc0NTM@._V1_SY500_CR0,0,345,500_AL_.jpg"
    },
    {
        "title": "Hum Dil De Chuke Sanam",
        "year": "1999",
        "genres": [
            "Comedy",
            "Drama",
            "Musical"
        ],
        "ratings": [
            5,
            9,
            2,
            4,
            1,
            2,
            10,
            5,
            7,
            3,
            3,
            10,
            10,
            6,
            2,
            8,
            1,
            9,
            6,
            8,
            10,
            8,
            3,
            3,
            7,
            6,
            1,
            8,
            2,
            5
        ],
        "poster": "MV5BZWI5ZWMxN2QtNjJmNS00M2EwLTg3ZmUtYzI5ODY3MWM2MzM1XkEyXkFqcGdeQXVyNDk3Mzg2OTc@._V1_SY500_CR0,0,350,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT188M",
        "releaseDate": "1999-06-18",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "When Sameer asks for Nandini's hand in marriage her family refuses. They have already chosen a husband for their daughter. Sameer returns to Italy. When Vanraj, Nandini's husband realizes that his new bride has been in love with someone else, he is prepared to sacrifice his love for her and take her to Italy to be reunited with her true love, Sameer.                Written by\nTapestry",
        "actors": [
            "Salman Khan",
            "Ajay Devgn",
            "Aishwarya Rai Bachchan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWI5ZWMxN2QtNjJmNS00M2EwLTg3ZmUtYzI5ODY3MWM2MzM1XkEyXkFqcGdeQXVyNDk3Mzg2OTc@._V1_SY500_CR0,0,350,500_AL_.jpg"
    },
    {
        "title": "1 - Nenokkadine",
        "year": "2014",
        "genres": [
            "Action",
            "Musical",
            "Mystery"
        ],
        "ratings": [
            10,
            3,
            7,
            6,
            5,
            5,
            9,
            1,
            3,
            10,
            7,
            10,
            2,
            5,
            8,
            10,
            6,
            2,
            7,
            1,
            6,
            3,
            6,
            7,
            9,
            4,
            2,
            5,
            4,
            1
        ],
        "poster": "MV5BNzcwMzkwODE1NF5BMl5BanBnXkFtZTgwNzA1NzAwMTE@._V1_SY350_CR0,0,242,350_AL_.jpg",
        "contentRating": "",
        "duration": "PT170M",
        "releaseDate": "2014-01-10",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Gautham (Mahesh Babu) is in search of the identity of his parents who were killed. He faces a psychological disorder which makes the search even more difficult. taking support of sameera(Kriti ) and figuring out ways to get to know what happened in the past makes the story.                Written by\nD Lokesh Reddy",
        "actors": [
            "Mahesh Babu",
            "Kriti Sanon",
            "Nassar"
        ],
        "imdbRating": 8.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzcwMzkwODE1NF5BMl5BanBnXkFtZTgwNzA1NzAwMTE@._V1_SY350_CR0,0,242,350_AL_.jpg"
    },
    {
        "title": "Jolly LLB 2",
        "year": "2017",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            5,
            3,
            1,
            9,
            2,
            4,
            10,
            1,
            8,
            8,
            6,
            7,
            6,
            8,
            3,
            10,
            10,
            7,
            10,
            7,
            8,
            6,
            4,
            6,
            5,
            9,
            3,
            8,
            5,
            2
        ],
        "poster": "MV5BMDY5MzFlYzEtNTg0YS00OGM5LWI1ZDMtZDkxN2Y2OTI1NGUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjM1NjkwMDI@._V1_SY480_SX360_AL_.jpg",
        "contentRating": "",
        "duration": "PT137M",
        "releaseDate": "2017-02-10",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jolly is a clumsy lawyer who is faced with representing the most critical court case of his career.",
        "actors": [
            "Ram Gopal Bajaj",
            "Sudhanva Deshpande",
            "Avijit Dutt"
        ],
        "imdbRating": 7.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDY5MzFlYzEtNTg0YS00OGM5LWI1ZDMtZDkxN2Y2OTI1NGUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjM1NjkwMDI@._V1_SY480_SX360_AL_.jpg"
    },
    {
        "title": "Raanjhanaa",
        "year": "2013",
        "genres": [
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            10,
            7,
            3,
            1,
            3,
            8,
            5,
            4,
            7,
            3,
            7,
            4,
            6,
            6,
            7,
            3,
            3,
            4,
            4,
            10,
            4,
            4,
            9,
            7,
            6,
            2,
            9,
            4,
            1
        ],
        "poster": "MV5BMjE2MDA3MTQ4MF5BMl5BanBnXkFtZTcwNjE5NjY0OQ@@._V1_SY500_CR0,0,319,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT140M",
        "releaseDate": "2013-06-21",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The pundit's son Kundan (Dhanush) has fallen for the girl at first sight. That they're both kids makes us dismiss it as a meaningless crush. But a few years later, the boy is still in love with the girl, Zoya (Sonam Kapoor). When she's in school, he follows her around holding her hand and getting slapped in the process. Finally, she relents because of his \"consistency\". The film shifts cities when Zoya gets into JNU (Jawaharlal Nehru University), and through her, we are introduced to the idealistic and political culture of the place. She discovers a long-lost strength as she confronts and then falls for student leader Akram (Abhay Deol). The film takes a turn when Zoya returns to her hometown after eight long years only to find some things changed, and others surprisingly the same.                Written by\nSonia Chopra",
        "actors": [
            "Dhanush",
            "Sonam Kapoor",
            "Mohammed Zeeshan Ayyub"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE2MDA3MTQ4MF5BMl5BanBnXkFtZTcwNjE5NjY0OQ@@._V1_SY500_CR0,0,319,500_AL_.jpg"
    },
    {
        "title": "Hungama",
        "year": "2003",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            5,
            5,
            8,
            8,
            1,
            8,
            10,
            8,
            8,
            9,
            10,
            6,
            3,
            4,
            10,
            4,
            4,
            8,
            5,
            6,
            3,
            2,
            3,
            2,
            8,
            5,
            8,
            10,
            6,
            8
        ],
        "poster": "MV5BMTA5NTQyMzU1MDBeQTJeQWpwZ15BbWU4MDE5NTY1MTQx._V1_SY250_CR0,0,171,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT153M",
        "releaseDate": "2003-08-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The story of a bunch of misfits whose misconception about each others backgrounds end up in a series of chaotic, yet comic outcomes. Aftab and Rimi play two strangers who have to pretend that are a married couple in order to get a place to live. Paresh Rawal plays a rich, yet ground to earth businessman whose business is named after his wife Anjali. Akshaye Khanna plays a young man starting a new business in electronic ware. Things get complicated when Rimi Sen goes to Paresh Rawal's house in search of a job & meets Akshaye Khanna who falls in love with her thinking she is Paresh Rawal's daughter. Paresh Rawal's wife thinks that he is having an affair with Rimi Sen & while Paresh Rawal thinks his wife is having an affair with Akshaye Khanna due to Rimi Sen and her having the same name. Then comes in Shakti Kapoor whose daughter falls in love with a guy pretending to be Paresh Rawal's son and soon everything gets out of control.                Written by\nNeo, Wellington, NZ",
        "actors": [
            "Akshaye Khanna",
            "Aftab Shivdasani",
            "Rimi Sen"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA5NTQyMzU1MDBeQTJeQWpwZ15BbWU4MDE5NTY1MTQx._V1_SY250_CR0,0,171,250_AL_.jpg"
    },
    {
        "title": "Khakee",
        "year": "2004",
        "genres": [
            "Action",
            "Adventure",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            5,
            6,
            7,
            6,
            7,
            8,
            10,
            4,
            3,
            5,
            8,
            1,
            7,
            10,
            8,
            3,
            8,
            6,
            10,
            3,
            3,
            2,
            4,
            5,
            6,
            8,
            6,
            1
        ],
        "poster": "MV5BMTY3MDE4MDY1Ml5BMl5BanBnXkFtZTcwMzE2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT174M",
        "releaseDate": "2004-01-23",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "DCP Anant Shrivastav (Amitabh Bachchan) has been assigned the mission to escort terrorist Iqbal Ansari (Atul Kulkarni) from Chandangarh to Mumbai. His terrorist organization are determined to obtain him again. The plan for this is led by Yashwant Angre (Ajay Devgan), a ruthless killer and a former police officer. Anant's team consists of Inspector Shekhar Sachdev (Akshay Kumar), rookie cop Ashwin Gupte (Tusshar Kapoor) and two more inspectors. Soon Mahalakshmi (Aishwarya Rai) joins them as she is the only witness to have seen Yashwant. The team are armed and ready to go but danger lurks everywhere as the terrorist organization are determined to make sure the officers do not make it to Mumbai. The trip turns into survival when the team are attacked at various times. Finally the team make it to an abandoned cottage in the forest but there is a shoot out and the team are heavily outnumbered. Shekhar tries to force an exchange but against Anant's and Ashwin's judgement. Finally Ansari, ...                Written by\ngavin@sunny_deol2009@yahoo.com",
        "actors": [
            "Amitabh Bachchan",
            "Akshay Kumar",
            "Ajay Devgn"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3MDE4MDY1Ml5BMl5BanBnXkFtZTcwMzE2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg"
    },
    {
        "title": "Rocket Singh: Salesman of the Year",
        "year": "2009",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            2,
            1,
            7,
            8,
            10,
            7,
            1,
            1,
            10,
            6,
            1,
            6,
            9,
            9,
            10,
            7,
            7,
            6,
            1,
            6,
            4,
            5,
            4,
            6,
            8,
            5,
            3,
            3,
            10,
            3
        ],
        "poster": "MV5BMTk1ODg4NzIxNl5BMl5BanBnXkFtZTcwNDAyOTg5Mg@@._V1_SY375_CR0,0,233,375_AL_.jpg",
        "contentRating": "",
        "duration": "PT150M",
        "releaseDate": "2009-12-11",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Harpreet Singh Bedi (Ranbir Kapoor) has just graduated, and his marks are, well, let's say a little embarrassing. But marks never stopped him from dreaming of an exciting and adventurous career, and they never will. 'Rocket Singh - Salesman of the Year' is the sometimes thoughtless, sometimes thoughtful story of a fresh graduate trying to find a balance between the maddening demands of the 'professional' way, and the way of his heart - and stumbling upon a crazy way which turned his world upside down, and his career right side up. Welcome to the world of sales, boss!                Written by\nDubai Internation Film Festival",
        "actors": [
            "Ranbir Kapoor",
            "Prem Chopra",
            "Gauhar Khan"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk1ODg4NzIxNl5BMl5BanBnXkFtZTcwNDAyOTg5Mg@@._V1_SY375_CR0,0,233,375_AL_.jpg"
    },
    {
        "title": "Dear Zindagi",
        "year": "2016",
        "genres": [
            "Drama",
            "Romance"
        ],
        "ratings": [
            1,
            7,
            1,
            4,
            8,
            5,
            4,
            9,
            3,
            4,
            1,
            8,
            3,
            1,
            3,
            4,
            9,
            3,
            4,
            7,
            8,
            7,
            6,
            9,
            1,
            3,
            10,
            4,
            2,
            10
        ],
        "poster": "MV5BZWQzYWI3ZGMtYzgyYy00OWZkLWEwODYtNGNiMTZhODBkNzUyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SY500_CR0,0,375,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT151M",
        "releaseDate": "2016-11-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "This is the story of Kaira, a budding cinematographer in search of perfect life. A chance encounter with Jug, an unconventional thinker, helps her gain new perspective about life. She discovers that happiness is all about finding comfort in life's imperfections.",
        "actors": [
            "Alia Bhatt",
            "Shah Rukh Khan",
            "Kunal Kapoor"
        ],
        "imdbRating": 8.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWQzYWI3ZGMtYzgyYy00OWZkLWEwODYtNGNiMTZhODBkNzUyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SY500_CR0,0,375,500_AL_.jpg"
    },
    {
        "title": "Jaane Tu... Ya Jaane Na",
        "year": "2008",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            8,
            9,
            1,
            2,
            1,
            7,
            8,
            2,
            8,
            2,
            4,
            6,
            3,
            6,
            3,
            5,
            1,
            1,
            1,
            1,
            5,
            3,
            5,
            8,
            3,
            7,
            4,
            10,
            2,
            2
        ],
        "poster": "MV5BMTk5NzI2MDkzOF5BMl5BanBnXkFtZTcwODA5NTk5Mw@@._V1_SY250_CR0,0,185,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT155M",
        "releaseDate": "2008-07-04",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "While on the way to the airport, Mala, who Jignesh Patel believes is going to be his future girlfriend, must listen to the romantic overtures of a group who are obsessed with the popular number 'Jaane Tu Ya Jaane Na' from the movie 'Aa Gale Lag Jaa'. The story is about Jai Singh Rathore and Aditi Wadia, two friends who are so close that the Wadias decide to get them married. But both disagree, and decide to seek soul mates for each other. With Aditi's help, Jai meets Meghna, and both fall in love with each other. Jai is introduced to her parents, who also approve of him. Aditi's is then introduced to Sushant Modi, who instantly finds approval, even with her reclusive brother, Amit. Mala anxiously awaits the climax as the story unfolds with many twists and turns.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Imran Khan",
            "Genelia D'Souza",
            "Manjari Phadnis"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk5NzI2MDkzOF5BMl5BanBnXkFtZTcwODA5NTk5Mw@@._V1_SY250_CR0,0,185,250_AL_.jpg"
    },
    {
        "title": "Madaari",
        "year": "2016",
        "genres": [
            "Adventure",
            "Crime",
            "Drama"
        ],
        "ratings": [
            9,
            2,
            4,
            10,
            10,
            3,
            3,
            10,
            7,
            5,
            9,
            8,
            10,
            4,
            8,
            3,
            3,
            4,
            7,
            4,
            1,
            9,
            9,
            8,
            3,
            2,
            8,
            2,
            5,
            10
        ],
        "poster": "MV5BZDFjODM0NDAtNGJkZC00NmRiLWI3NmYtZDFkYmRhYmE4Zjk3XkEyXkFqcGdeQXVyNTIwODMzNjc@._V1_SY500_CR0,0,346,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT133M",
        "releaseDate": "2016-07-22",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "'Madaari' is the story of a common man who sets out to avenge the death of his son caused by rampant corruption in the government. Losing the only family he had brings him to kidnap the home minister's son and bring those responsible to justice.                Written by\nKeith Francis Bacon",
        "actors": [
            "Irrfan Khan",
            "Jimmy Shergill",
            "Vishesh Bansal"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDFjODM0NDAtNGJkZC00NmRiLWI3NmYtZDFkYmRhYmE4Zjk3XkEyXkFqcGdeQXVyNTIwODMzNjc@._V1_SY500_CR0,0,346,500_AL_.jpg"
    },
    {
        "title": "Peepli (Live)",
        "year": "2010",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            9,
            3,
            6,
            6,
            3,
            8,
            6,
            10,
            4,
            5,
            7,
            3,
            5,
            10,
            2,
            4,
            6,
            3,
            7,
            7,
            4,
            2,
            4,
            6,
            4,
            10,
            7,
            5
        ],
        "poster": "MV5BMTgwMzEzNjYyNl5BMl5BanBnXkFtZTcwOTg1MDI3Mw@@._V1_SX346_CR0,0,346,499_AL_.jpg",
        "contentRating": "",
        "duration": "PT95M",
        "releaseDate": "2010-08-13",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In the lead up to state elections in the Indian village of Peepli, two poor farmers, Natha and Budhia, face losing their land over an unpaid bank loan. Desperate, they seek help from an apathetic local politician, who scornfully suggests they commit suicide to benefit from a government program that aids the families of indebted deceased farmers. When a journalist overhears Budhia urge Natha to \"do what needs to be done\" for the sake of their families, a media frenzy ignites around whether or not Natha will commit suicide.                Written by\nSundance Film Festival",
        "actors": [
            "Omkar Das Manikpuri",
            "Raghuvir Yadav",
            "Shalini Vatsa"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgwMzEzNjYyNl5BMl5BanBnXkFtZTcwOTg1MDI3Mw@@._V1_SX346_CR0,0,346,499_AL_.jpg"
    },
    {
        "title": "Dum Laga Ke Haisha",
        "year": "2015",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            2,
            3,
            7,
            4,
            9,
            7,
            2,
            7,
            9,
            3,
            5,
            9,
            10,
            2,
            3,
            4,
            9,
            7,
            4,
            10,
            10,
            3,
            4,
            4,
            10,
            10,
            4,
            2,
            2,
            1
        ],
        "poster": "MV5BMTg2Njg1OTg4OV5BMl5BanBnXkFtZTgwMjczNzM2NDE@._V1_SY389_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT110M",
        "releaseDate": "2015-02-27",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Prem Prakash Tiwari (Ayushmann Khurrana) listening to Kumar Sanu is the film's opening shot. Set in Haridwar, 1990s, the film captures the nascent feel of the town. Prem owns a cassette shop in the local market. His father is keen to get him hitched and the family goes to a local temple to meet Sandhya (Bhumi Pednekar). B.Ed, waiting for a teaching job, the most visible thing about her is her weight. Coming from a patriarchal cognitive set-up, she doesn't fit the quintessential idea of beautiful. And still, the school drop out Prem must marry her because he is incapable of attaining a girl with 'Juhi-Chawla-level-of-looks.' In an elaborate community-wedding ceremony, Prem and Sandhya get married. Their wedding night is uncomfortable with neither treading towards establishing conjugal relations. Prem has in his own reasons and the girl is naturally shy. Next morning on a call, she announces it to a friend and the whole family finds out.                Written by\nKing Motwani",
        "actors": [
            "Bhumi Pednekar",
            "Sanjay Mishra",
            "Ayushmann Khurrana"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2Njg1OTg4OV5BMl5BanBnXkFtZTgwMjczNzM2NDE@._V1_SY389_SX250_AL_.jpg"
    },
    {
        "title": "Baghban",
        "year": "2003",
        "genres": [
            "Drama",
            "Romance"
        ],
        "ratings": [
            2,
            10,
            9,
            4,
            4,
            9,
            6,
            9,
            1,
            9,
            10,
            5,
            2,
            3,
            5,
            2,
            9,
            3,
            8,
            1,
            4,
            10,
            2,
            3,
            10,
            9,
            7,
            2,
            3,
            8
        ],
        "poster": "MV5BMjA2NTEyODY4Ml5BMl5BanBnXkFtZTcwOTk2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg",
        "contentRating": "",
        "duration": "PT181M",
        "releaseDate": "2003-10-03",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Raj Malhotra and wife Pooja have four sons. The sons have settled down professionally and are quite independent. However, when Raj Malhotra retires, none of his children want to be burdened with the responsibility of taking care of their parents. Strangely, it is the adopted son who proves to be the most kind hearted of them all. Salman's girlfriend eventually marries him. The question is, will Raj and Pooja's sons learn the folly of their ways and turn over a new leaf?                Written by\ngavin@sunny_deol2009@yahoo.com",
        "actors": [
            "Amitabh Bachchan",
            "Hema Malini",
            "Aman Verma"
        ],
        "imdbRating": 7.5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA2NTEyODY4Ml5BMl5BanBnXkFtZTcwOTk2ODgzMQ@@._V1_SY250_CR0,0,176,250_AL_.jpg"
    }
]

const parentDiv = document.getElementById("library");
function displayData(moviesData){
    moviesData.forEach(function (movie) {
        const childDiv = document.createElement("div");
        childDiv.classList.add("movie-card");
        const title = document.createElement("h2");
        title.textContent = "Title: " + movie.title;
        const year = document.createElement("p");
        year.textContent = "Release Year: " + movie.year;
        const genres = document.createElement("p");
        genres.textContent = "Genre: " + movie.genres;
        const releaseDate = document.createElement("p");
        releaseDate.textContent = "Release Date: " + movie.releaseDate;
        const actors = document.createElement("p");
        actors.textContent = "Actors: " + movie.actors;
        const imdbRating = document.createElement("p");
        imdbRating.textContent = "IMDB Rating: " + movie.imdbRating;
        const posterurl = document.createElement("img");
        posterurl.setAttribute('src', movie.posterurl);
        posterurl.alt = movie.title;
        childDiv.append(posterurl, title, genres, year, releaseDate, actors, imdbRating);
        parentDiv.appendChild(childDiv);
    })
}
displayData(moviesData);